name: CI

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*.*.*' ]
  pull_request:
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  test:
    name: Python Tests
    runs-on: infra
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt pytest

      - name: Run tests
        run: |
          . .venv/bin/activate
          # Disable schedulers/scanners during tests
          export DISABLE_SCHEDULER=1
          export DISABLE_SCANNING=1
          pytest -q

  build:
    name: Build Docker Image
    runs-on: infra
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image metadata
        id: meta
        shell: bash
        run: |
          REPO_LOWER="${GITHUB_REPOSITORY,,}"
          IMAGE_REF="${REPO_LOWER}"
          TAG_SHA="${GITHUB_SHA}"
          TAG_REF="${GITHUB_REF##*/}"
          echo "image_ref=${IMAGE_REF}" >> $GITHUB_OUTPUT
          echo "tag_sha=${TAG_SHA}" >> $GITHUB_OUTPUT
          echo "tag_ref=${TAG_REF}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker build -t "${{ steps.meta.outputs.image_ref }}:${{ steps.meta.outputs.tag_sha }}" .

